//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SYSTEM_SECURITY_CRYPTOGRAPHY_NETMF_H_
#define _SYSTEM_SECURITY_CRYPTOGRAPHY_NETMF_H_

#include <TinyCLR_Interop.h>
struct Library_System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random
{
    static const int FIELD_STATIC___lock = 0;
    static const int FIELD_STATIC___referenceCount = 1;

    static const int FIELD___enabled = 1;

    TINYCLR_NATIVE_DECLARE(NativeEnable___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(NativeDisable___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(NativeGetBytes___STATIC__VOID__SZARRAY_U1);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_Security_Cryptography_Netmf;

#endif  //_SYSTEM_SECURITY_CRYPTOGRAPHY_NETMF_H_
