//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "System_Security_Cryptography_Netmf.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random::NativeEnable___STATIC__VOID,
    Library_System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random::NativeDisable___STATIC__VOID,
    Library_System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random::NativeGetBytes___STATIC__VOID__SZARRAY_U1,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_Security_Cryptography_Netmf =
{
    "System.Security.Cryptography.Netmf", 
    0x8119DF0D,
    method_lookup
};

