//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "System_Security_Cryptography_Netmf.h"
#include "System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random.h"

using namespace System::Security::Cryptography;


HRESULT Library_System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random::NativeEnable___STATIC__VOID( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        Stm32F4Random::NativeEnable( hr );
        TINYCLR_CHECK_HRESULT( hr );
    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random::NativeDisable___STATIC__VOID( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        Stm32F4Random::NativeDisable( hr );
        TINYCLR_CHECK_HRESULT( hr );
    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_System_Security_Cryptography_Netmf_System_Security_Cryptography_Stm32F4Random::NativeGetBytes___STATIC__VOID__SZARRAY_U1( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_TypedArray_UINT8 param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ARRAY( stack, 0, param0 ) );

        Stm32F4Random::NativeGetBytes( param0, hr );
        TINYCLR_CHECK_HRESULT( hr );
    }
    TINYCLR_NOCLEANUP();
}
